version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          dependency_type: "production"
          update_type: "security"
