@auth0_base_url=https://httpbin.org/post?test=
@user_auth_client_id=client_id
@user_auth_client_secret=client_secret
@user_auth_username=username
@user_auth_password=pwd


### User Login
# @name login
POST {{auth0_base_url}}/oauth/token
Content-Type: application/json

{
 "client_id": "{{user_auth_client_id}}",
 "client_secret": "{{user_auth_client_secret}}",
 "grant_type": "http://someauth.com/realm",
 "username": "{{user_auth_username}}",
 "password": "{{user_auth_password}}",
 "audience": "an/audience",
 "realm": "Username-Password-Authentication",
 "scope": "openid"
}
> ./login.js