
POST https://httpbin.org/anything
Content-Type: application/x-www-form-urlencoded
accept: application/json

email=user@domain.loc&password=1



POST https://httpbin.org
  /anything
Content-Type: application/x-www-form-urlencoded
accept: application/json

email=user@domain.loc&password=1



POST https://httpbin.org
  /anything
  ?test=test
Content-Type: application/x-www-form-urlencoded
accept: application/json

email=user@domain.loc&password=1

###

POST https://httpbin.org/anything
Content-Type: application/x-www-form-urlencoded
accept: application/json

email=user@domain.loc&password=2

> ./intellij.js

POST https://httpbin.org/anything
Content-Type: application/x-www-form-urlencoded
accept: application/json

email=user@domain.loc&password=3



> {% client.global.set("email", response.body.form.email); %}


###
# @injectVariables

@testVariable=foo

POST https://httpbin.org/anything
accept: application/json


< ./variables.json