# @name ubuntu
GET https://releases.ubuntu.com/20.04.1/ubuntu-20.04.1-desktop-amd64.iso

###

https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css

###

https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js

###

/robots.txt

###

https://github.com/AnWeber/httpbook/blob/main/.eslintrc.yml

###

POST https://httpbin.org/response-headers?Content-Type=text%2Fyaml
spring.profile.active: local,dev