
@user = doe
@password = 12345678

###

GET /basic-auth/{{user}}/{{password}}
Authorization: Basic {{user}} {{password}}

{{
  const assert = require('assert');
  assert.equal(response.parsedBody.authenticated, true, "Basic Auth works");
}}


GET /basic-auth/{{user}}/{{password}}
Authorization: Basic {{Buffer.from( user + ":" + password).toString('base64')}}

{{
  const assert = require('assert');
  assert.equal(response.parsedBody.authenticated, true, "Basic Auth works");
}}