
@host = https://httpbin.org
@user = doe
@password = 12345678


GET /digest-auth/auth/{{user}}/{{password}}
Authorization: Digest {{user}} {{password}}

{{
  const assert = require('assert');
  test("Digest Auth works", () => {
    assert.equal(response.parsedBody.authenticated, true, );
  });
}}