
/*
# httpbin.org (0.9.2)

> [ Base URL: httpbin.org/ ]

A simple HTTP Request & Response Service

**Run locally:** `$ docker run -p 80:80 kennethreitz/httpbin`

[the developer - Website](https://kennethreitz.org/)
[Send email to the developer](me@kennethreitz.org)
*/


/*
## Http Methods

Testing different HTTP verbs
*/


/*
## Status Codes

Generates responses with given status code
*/

DELETE https://httpbin.org/delete 

HTTP/1.1 200 - OK
date: Mon, 21 Jun 2021 19:38:00 GMT
content-type: application/json
content-length: 361
connection: close
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Host": "httpbin.org", 
    "User-Agent": "httpyac", 
    "X-Amzn-Trace-Id": "Root=1-60d0ea98-6446cd5e7dfa0a805da95cad"
  }, 
  "json": null, 
  "origin": "79.243.57.74", 
  "url": "https://httpbin.org/delete"
}

###

GET https://httpbin.org/get

HTTP/1.1 200 - OK
date: Mon, 21 Jun 2021 19:38:05 GMT
content-type: application/json
content-length: 295
connection: close
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Host": "httpbin.org", 
    "User-Agent": "httpyac", 
    "X-Amzn-Trace-Id": "Root=1-60d0ea9d-3dfb873f497a9e6d50b2eccc"
  }, 
  "origin": "79.243.57.74", 
  "url": "https://httpbin.org/get"
}

###

PATCH https://httpbin.org/patch

HTTP/1.1 200 - OK
date: Mon, 21 Jun 2021 19:38:07 GMT
content-type: application/json
content-length: 388
connection: close
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Content-Length": "0", 
    "Host": "httpbin.org", 
    "User-Agent": "httpyac", 
    "X-Amzn-Trace-Id": "Root=1-60d0ea9f-7e49d0a404e13ce7386fb746"
  }, 
  "json": null, 
  "origin": "79.243.57.74", 
  "url": "https://httpbin.org/patch"
}

###

POST https://httpbin.org/post

HTTP/1.1 200 - OK
date: Mon, 21 Jun 2021 19:38:10 GMT
content-type: application/json
content-length: 387
connection: close
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Content-Length": "0", 
    "Host": "httpbin.org", 
    "User-Agent": "httpyac", 
    "X-Amzn-Trace-Id": "Root=1-60d0eaa2-3379384b530308d96e9ade95"
  }, 
  "json": null, 
  "origin": "79.243.57.74", 
  "url": "https://httpbin.org/post"
}

###

PUT https://httpbin.org/put

HTTP/1.1 200 - OK
date: Mon, 21 Jun 2021 19:38:12 GMT
content-type: application/json
content-length: 386
connection: close
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Content-Length": "0", 
    "Host": "httpbin.org", 
    "User-Agent": "httpyac", 
    "X-Amzn-Trace-Id": "Root=1-60d0eaa4-1a5b7a7507929e2d412e650a"
  }, 
  "json": null, 
  "origin": "79.243.57.74", 
  "url": "https://httpbin.org/put"
}

###

DELETE https://httpbin.org/status/200

HTTP/1.1 200 - OK
date: Mon, 21 Jun 2021 19:38:15 GMT
content-type: text/html; charset=utf-8
content-length: 0
connection: close
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

###

GET https://httpbin.org/status/200

HTTP/1.1 200 - OK
date: Mon, 21 Jun 2021 19:38:18 GMT
content-type: text/html; charset=utf-8
content-length: 0
connection: close
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

###

PATCH https://httpbin.org/status/200

HTTP/1.1 200 - OK
date: Mon, 21 Jun 2021 19:38:24 GMT
content-type: text/html; charset=utf-8
content-length: 0
connection: close
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

###

POST https://httpbin.org/status/200

HTTP/1.1 200 - OK
date: Mon, 21 Jun 2021 19:38:22 GMT
content-type: text/html; charset=utf-8
content-length: 0
connection: close
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

###

PUT https://httpbin.org/status/200

HTTP/1.1 200 - OK
date: Mon, 21 Jun 2021 19:38:30 GMT
content-type: text/html; charset=utf-8
content-length: 0
connection: close
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true