GET /get

POST /post

{
  "name": "john smith"
}

PUT /put

{
  "name": "john smith"
}

DELETE /delete

PATCH /patch

{
  "name": "john smith"
}

HEAD /get

OPTIONS /get

CONNECT /connect

TRACE /trace

PROPFIND /get

PROPPATCH /get

MKCOL /get

COPY /get

MOVE /get

LOCK /get

UNLOCK /get

CHECKOUT /get

CHECKIN /get

REPORT /get

MERGE /get

MKACTIVITY /get

MKWORKSPACE /get

VERSION-CONTROL /get

BASELINE-CONTROL /get