export enum HttpSymbolKind{
  request,
  requestLine,
  requestMethod,
  requestUrl,
  requestHeader,
  requestHeaderKey,
  requestHeaderValue,
  script,
  metaParam,
  metaParamKey,
  metaParamValue,
  variable,
  variableName,
  varialbeValue,
}