export enum HttpSymbolKind{
  request = "request",
  requestLine = "requestLine",
  requestMethod = "requestMethod",
  requestUrl = "requestUrl",
  requestHeader ="requestHeader",
  requestHeaderKey = "requestHeaderKey",
  requestHeaderValue = "requestHeaderValue",
  script = "script",
  metaData = "metaData",
  metaDataKey = "metaDataKey",
  metaDataValue = "metaDataValue",
  variable = "variable",
  variableName = "variableName",
  varialbeValue = "varialbeValue",
}