
GET /json

{{
  const { expect } = require('chai');
  test('status code 200', () => {
    expect(response.statusCode).to.equal(200)
  });
}}

GET https://cat-fact.herokuapp.com/facts/random HTTP/1.1


{{
  const { expect } = require('chai');
  test('status code is 200', () => {
      expect(response.statusCode).to.equal(200);
  });

  test('content is not null', () => {
      expect(response.body).to.not.be.null;
  });

  test('type is cat', () => {
      expect(response.parsedBody.type).to.equal('cat');
  });
}}

###

GET https://cat-fact.herokuapp.com/facts/random HTTP/1.1


{{
  const { expect } = require('chai');
  test('status code is 200', () => {
      expect(response.statusCode).to.equal(200);
  });

  test('content is not null', () => {
      expect(response.body).to.not.be.null;
  });


  test('text equals hello world', () => {
      expect(response.parsedBody.text).to.equal('hello world');
  });

  test('type is cat', () => {
      expect(response.parsedBody.type).to.equal('cat');
  });
}}

###

GET https://cat-fact.herokuapp.com/facts/random HTTP/1.1


{{
  const { expect } = require('chai');
  test('status code is 400', () => {
      expect(response.statusCode).to.equal(400);
  });

  test('text equals hello world', () => {
      expect(response.parsedBody.text).to.equal('hello world');
  });
}}


###

GET https://cat-fact.herokuapp.com/facts/random HTTP/1.1