{{
  // script gets executed only once per file
  // use send all to test
  const crypto = require('crypto');
  const date = new Date();
  const url = host;
  const method = 'GET';

  const requestUri = url.substring(url.indexOf('/anything'), url.indexOf('?') > 0 ? url.indexOf('?') : url.length);
  const timeInMillis = date.getTime() - date.getMilliseconds();

  const signature = `${method}\u2028${requestUri}\u2028${timeInMillis}`;
  const signatureBase64 = crypto.createHmac('sha256', 'secret').update(signature).digest("base64");
  exports.authDate = date.toUTCString();
  exports.authentcation = `Basic ${signatureBase64}`;
}}


###
GET /anything
Authentication: {{authentcation}}
Date: {{authDate}}


GET /anything
Authentication: {{authentcation}}
Date: {{authDate}}

