
GET /json

{{
  const assert = require('assert');
  test("Post Request Scripts does not Works", () => {
    assert.equal(response.parsedBody.slideshow.title, 'Sample Slide Show');
  });
}}

GET /json

{{
  const assert = require('assert');
  test("Post Request Scripts does not Works", () => {
    assert.equal(response.parsedBody.slideshow.title, 'fail');
  });
}}